# Generated by Django 5.0.4 on 2024-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_video_video_video_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableopening',
            old_name='end_date',
            new_name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='availableopening',
            name='start_date',
        ),
        migrations.AddField(
            model_name='availableopening',
            name='link_to_opening',
            field=models.URLField(default=''),
        ),
    ]
