# Generated by Django 5.0.4 on 2024-09-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_end_date_availableopening_deadline_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableopening',
            old_name='deadline_date',
            new_name='date_today',
        ),
        migrations.AddField(
            model_name='availableopening',
            name='department',
            field=models.CharField(max_length=255, null=True),  # ← FIXED: removed default=None, added null=True
        ),
    ]