# Generated by Django 5.0.4 on 2024-09-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_deadline_date_availableopening_date_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableopening',
            name='no',
        ),
    ]
