# Generated by Django 5.0.4 on 2024-09-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_news_recentactivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentactivities',
            name='link_url',
            field=models.URLField(null=True),
        ),
    ]
