# Generated by Django 5.0.4 on 2024-09-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_recentactivities_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableopening',
            name='link_to_opening',
            field=models.URLField(null=True),
        ),
    ]
