# Generated by Django 5.0.4 on 2024-09-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_availableopening_link_to_opening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentactivities',
            old_name='news_text',
            new_name='text',
        ),
    ]
