# Generated by Django 5.0.4 on 2024-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_news_text_recentactivities_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableopening',
            name='link_to_opening',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='privitasationusers',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privitasationusers',
            name='kra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privitasationusers',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='privitasationusers',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recentactivities',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
