# Generated by Django 5.0.4 on 2024-09-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_availableopening_link_to_opening_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_text',
            new_name='text',
        ),
    ]
