# Generated by Django 5.1.1 on 2025-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_historicalavailableopening_historicalgallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableopening',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalavailableopening',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
