# Generated by Django 4.2 on 2025-07-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_boardmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmember',
            old_name='full_name',
            new_name='name',
        ),
    ]
