# Generated by Django 4.2 on 2025-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='image',
            field=models.ImageField(upload_to='management/'),
        ),
    ]
