# Generated by Django 4.2 on 2025-07-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('document_link', models.URLField()),
            ],
        ),
    ]
