# Generated by Django 5.2.6 on 2025-12-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_faq'),
    ]

    operations = [
    ]
